//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archides.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ContactUsID { get; set; }
        public string Emri { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Mesazhi { get; set; }
    }
}
