//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archides.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int MediaID { get; set; }
        public Nullable<int> ProjektiID { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public Nullable<int> LlojiArkitekturaID { get; set; }
        public string MediaPath { get; set; }
    
        public virtual LlojiArkitektura LlojiArkitektura { get; set; }
        public virtual MediaType MediaType { get; set; }
        public virtual Projekti Projekti { get; set; }
    }
}
