//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archides.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Useri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Useri()
        {
            this.Lajmis = new HashSet<Lajmi>();
            this.Projektis = new HashSet<Projekti>();
            this.ProjektiUsers = new HashSet<ProjektiUser>();
        }
    
        public int UserID { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public string Gjinia { get; set; }
        public Nullable<int> Vendlindja { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Datelindja { get; set; }
        public string Email { get; set; }
        public string Telefoni { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Pershkrimi { get; set; }
        public string Foto { get; set; }
        public Nullable<int> RoliID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lajmi> Lajmis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekti> Projektis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektiUser> ProjektiUsers { get; set; }
        public virtual Qyteti Qyteti { get; set; }
        public virtual Roli Roli { get; set; }
    }
}
